### ISSUE TITLE
Password with &

### ISSUE THREAD

**Issue by adawi9** [amitanmol/OneHubOAuth#1]
I used you code to get access token from asp.net webapi, but the issue is when the password containes & character it is failed

**Comment by amitanmol** [comment]
You can not use this code in ASP.Net. This code is only for macOS and iOS written in Objective C, as you can see the description/readme of this code.

Let me know if you need any other help.

**Comment by adawi9** [comment]
Yes I know that (I'm iOS Developer)
What I said, this code is can be hacked when you send any password contains & character

**Comment by amitanmol** [comment]
This is how the request can be done for onehub to get auth token. I tried lots of ways but failed, only this one worked.

Let me know how do you think it should be. If you have any working code to get onehub auth token, please share.
